player_manager.AddValidModel( "Combine Fodder", 			"models/Player/combine_fodder.mdl" ) 
player_manager.AddValidModel( "Combine Infantry", 			"models/player/combine_infantry.mdl" )  
player_manager.AddValidModel( "Combine Opad", 				"models/player/combine_opad.mdl" )  
player_manager.AddValidModel( "Combine Pilot", 				"models/player/combine_pilot.mdl" )  
player_manager.AddValidModel( "Combine Ranger", 			"models/player/combine_ranger.mdl" ) 
player_manager.AddValidModel( "Combine Shotgunner", 		"models/player/combine_shotgunner.mdl" ) 
player_manager.AddValidModel( "RTB Combine Prisongaurd", 	"models/player/combine_soldier_pguard2.mdl" ) 
player_manager.AddValidModel( "Combine Urban 1", 			"models/player/combine_urban1.mdl" ) 
player_manager.AddValidModel( "Combine Urban 2", 			"models/player/combine_urban2.mdl" ) 
player_manager.AddValidModel( "Combine Trenchcoat", 		"models/player/combinetrenchcoat.mdl" ) 
player_manager.AddValidModel( "Consul", 					"models/player/consul.mdl" ) 
player_manager.AddValidModel( "Cremator", 					"models/player/cremator.mdl" ) 
player_manager.AddValidModel( "E3 Soldier", 				"models/player/e3_soldier1.mdl" ) 
player_manager.AddValidModel( "E3 Assassin", 				"models/player/e3assassin.mdl" ) 
player_manager.AddValidModel( "E3 Combine Prisongaurd", 	"models/player/e3combine_pgaurd.mdl" ) 
player_manager.AddValidModel( "E3 Combine Shotgunner", 		"models/player/e3combine_shotgunner2.mdl" ) 
player_manager.AddValidModel( "RTB Combine Sniper", 		"models/player/rtbcombine_sniper.mdl" )
player_manager.AddValidModel( "RTB Combine Sniper (Camo)", 		"models/player/rtbcombine_sniperc3.mdl" )
player_manager.AddValidModel( "Cremator", 					"models/Player/cremator.mdl" ) 
player_manager.AddValidModel( "E3 Police Trenchcoat 2", 		"models/player/e3policetrench2.mdl" )  
player_manager.AddValidModel( "E3 Elite Metrocop", 			"models/player/e3_cpelite.mdl" )  
player_manager.AddValidModel( "E3 Combine Trenchcoat", 		"models/player/combinetrenchcoat.mdl" ) 
player_manager.AddValidModel( "E3 Civil Protection",		"models/player/e3metrocop.mdl" ) 
player_manager.AddValidModel( "E3 Police Trenchcoat", 		"models/player/E3policetrench.mdl" ) 
player_manager.AddValidModel( "RTB Civil Protection", 		"models/player/rtbpolice.mdl" ) 
player_manager.AddValidModel( "E3 Female 1", 				"models/player/beta/female_01.mdl" ) 
player_manager.AddValidModel( "E3 Female 2", 				"models/player/beta/female_02.mdl" ) 
player_manager.AddValidModel( "E3 Female 4", 				"models/player/beta/female_04.mdl" ) 
player_manager.AddValidModel( "E3 Female 6",				"models/player/beta/female_06.mdl" ) 
player_manager.AddValidModel( "E3 Male 2",					"models/player/beta/male_02.mdl" ) 
player_manager.AddValidModel( "E3 Male 4", 					"models/player/beta/male_04.mdl" ) 
player_manager.AddValidModel( "E3 Male 5", 					"models/player/beta/e3male_05.mdl" )
player_manager.AddValidModel( "E3 Female 1 2", 				"models/player/beta02/female_01.mdl" ) 
player_manager.AddValidModel( "E3 Alyx", 					"models/Player/e3alyx.mdl" ) 
player_manager.AddValidModel( "E3 Classic Zombie", 			"models/player/e3classic.mdl" )  
player_manager.AddValidModel( "RTB Elaine", 				"models/player/elaine.mdl" )  
player_manager.AddValidModel( "Kraken Base Mossman", 		"models/player/kbmossman.mdl" )   
player_manager.AddValidModel( "E3 Animal", 					"models/player/animal.mdl" ) 
player_manager.AddValidModel( "E3 Gasmask Citizen", 		"models/player/Citizen_17.mdl" ) 
player_manager.AddValidModel( "E3 Cohrt", 					"models/player/e3cohrt.mdl" ) 
player_manager.AddValidModel( "E3 Barney", 					"models/player/e3barney.mdl" ) 
player_manager.AddValidModel( "E3 Eli", 					"models/player/e3eli.mdl" ) 
player_manager.AddValidModel( "Captain Vance", 				"models/player/vance.mdl" ) 
player_manager.AddValidModel( "E3 Grigori", 				"models/player/e3grigori.mdl" ) 
player_manager.AddValidModel( "E3 Gman", 					"models/player/e3gman.mdl" ) 
player_manager.AddValidModel( "E3 Odell", 					"models/player/e3odell.mdl" ) 

list.Set( "PlayerOptionsModel",  "Combine Fodder", 				"models/Player/combine_fodder.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Infantry", 			"models/Player/combine_infantry.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Opad", 				"models/player/combine_opad.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Pilot", 				"models/player/combine_pilot.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Ranger",				"models/player/combine_ranger.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Shotgunner", 			"models/player/combine_shotgunner.mdl" )
list.Set( "PlayerOptionsModel",  "RTB Combine Prisongaurd", 	"models/player/combine_soldier_pguard2.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Urban 1", 			"models/player/combine_urban1.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Urban 2", 			"models/player/combine_urban2.mdl" )
list.Set( "PlayerOptionsModel",  "Combine Trenchcoat",			"models/player/combinetrenchcoat.mdl" )
list.Set( "PlayerOptionsModel",  "Consul", 						"models/player/consul.mdl" )
list.Set( "PlayerOptionsModel",  "Cremator", 					"models/player/cremator.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Soldier", 					"models/player/e3_soldier1.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Assassin", 				"models/player/e3assassin.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Combine Prisongaurd", 		"models/player/e3combine_pgaurd.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Combine Shotgunner", 		"models/player/e3combine_shotgunner2.mdl" )
list.Set( "PlayerOptionsModel",  "RTB Combine Sniper", 			"models/player/rtbcombine_sniper.mdl" )
list.Set( "PlayerOptionsModel",  "RTB Combine Sniper (Camo)", 			"models/player/rtbcombine_sniperc3.mdl" )
list.Set( "PlayerOptionsModel",  "Cremator", 					"models/Player/cremator.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Police Trenchcoat 2", 		"models/Player/e3policetrench2.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Elite Metrocop", 			"models/player/e3_cpelite.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Combine Trenchcoat", 		"models/player/combinetrenchcoat.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Civil Protection", 		"models/player/e3metrocop.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Police Trenchcoat",		"models/player/E3policetrench.mdl" )
list.Set( "PlayerOptionsModel",  "RTB Civil Protection", 		"models/player/rtbpolice.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Female 1", 				"models/player/beta/female_01.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Female 2", 				"models/player/beta/female_02.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Female 4", 				"models/player/beta/female_04.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Female 6", 				"models/player/beta/female_06.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Male 2", 					"models/player/beta/male_02.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Male 4", 					"models/player/beta/male_04.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Male 5", 					"models/player/beta/e3male_05.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Female 1 2", 				"models/player/beta02/female_01.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Alyx",						"models/Player/e3alyx.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Classic Zombie", 			"models/Player/e3classic.mdl" )
list.Set( "PlayerOptionsModel",  "RTB Elaine", 					"models/player/elaine.mdl" )
list.Set( "PlayerOptionsModel",  "Kraken Base Mossman", 		"models/player/kbmossman.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Animal", 					"models/player/animal.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Gasmask Citizen", 			"models/player/citizen_17.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Cohrt", 					"models/player/e3cohrt.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Barney", 					"models/player/e3barney.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Eli", 						"models/player/e3Eli.mdl" )
list.Set( "PlayerOptionsModel",  "Captain Vance", 				"models/player/vance.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Grigori", 					"models/player/e3grigori.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Gman", 					"models/player/e3gman.mdl" )
list.Set( "PlayerOptionsModel",  "E3 Odell", 					"models/player/e3odell.mdl" )